import {
  Database,
  AlertCircle,
  CheckCircle2,
  Clock,
  Globe,
  Users,
  Zap,
  Bot,
  TrendingUp,
  BarChart3,
} from "lucide-react"

// ─── Catalogs Mock Data ───────────────────────────────────────────────────────

export const catalogMetrics = [
  {
    title: "Total Products",
    value: "124,892",
    description: "Total items in master catalog",
    icon: Database,
    trend: "up",
    change: "+1.2%",
  },
  {
    title: "Active Listings",
    value: "118,440",
    description: "Eligible for campaigns",
    icon: CheckCircle2,
    trend: "up",
    change: "+0.8%",
  },
  {
    title: "Issues Found",
    value: "482",
    description: "Items requiring data fixes",
    icon: AlertCircle,
    trend: "down",
    change: "-12%",
  },
  {
    title: "Last Sync",
    value: "8m ago",
    description: "Auto-sync every 6 hours",
    icon: Clock,
    trend: "up",
    change: "On schedule",
  },
]

export const productFeeds = [
  {
    id: "f1",
    name: "Realry Master Feed",
    source: "realry.com · Google Shopping XML",
    status: "healthy",
    items: 66800,
    health: 98,
    issues: 12,
    syncProgress: 100,
    lastSync: "8 min ago",
    nextSync: "5h 52m",
    schedule: "Every 6 hours",
  },
  {
    id: "f2",
    name: "Sneakers123 Feed",
    source: "sneakers123.com · Meta Commerce CSV",
    status: "healthy",
    items: 31450,
    health: 98,
    issues: 8,
    syncProgress: 100,
    lastSync: "8 min ago",
    nextSync: "5h 52m",
    schedule: "Every 6 hours",
  },
  {
    id: "f3",
    name: "FlexDog Luxury",
    source: "flexdog.com · Google Shopping XML",
    status: "warning",
    items: 16200,
    health: 88,
    issues: 284,
    syncProgress: 100,
    lastSync: "2h ago",
    nextSync: "4h",
    schedule: "Every 6 hours",
  },
  {
    id: "f4",
    name: "StylMatch Creator",
    source: "stylmatch.com · Custom API",
    status: "syncing",
    items: 3990,
    health: 65,
    issues: 178,
    syncProgress: 42,
    lastSync: "Syncing now",
    nextSync: "—",
    schedule: "Continuous",
  },
]

export const feedIssues = [
  {
    id: "i1",
    title: "Missing / Low-res Image",
    count: 178,
    impact: "High",
    revenueAtRisk: "$6.2K",
    suppressedImpressions: "184K",
    description:
      "Items missing a primary image or resolution < 800px. High impact on CTR and AI match eligibility.",
    category: "Media",
  },
  {
    id: "i2",
    title: "Price Mismatch / Missing",
    count: 52,
    impact: "High",
    revenueAtRisk: "$2.1K",
    suppressedImpressions: "48K",
    description:
      "Items where the feed price differs from the landing page, or price is absent. Causes Google Shopping disapprovals.",
    category: "Pricing",
  },
  {
    id: "i3",
    title: "Disapproved by Google",
    count: 14,
    impact: "High",
    revenueAtRisk: "$3.4K",
    suppressedImpressions: "29K",
    description:
      "Items blocked by Google's shopping policy. Requires manual review and resubmission to restore eligibility.",
    category: "Compliance",
  },
  {
    id: "i4",
    title: "Invalid / Missing GTIN",
    count: 142,
    impact: "Medium",
    revenueAtRisk: "$1.8K",
    suppressedImpressions: "62K",
    description:
      "Items missing global trade identifiers. Affects visibility in shopping comparison and price-match channels.",
    category: "Identifiers",
  },
  {
    id: "i5",
    title: "Title Exceeds 150 Characters",
    count: 96,
    impact: "Low",
    revenueAtRisk: "$400",
    suppressedImpressions: "11K",
    description:
      "Titles longer than 150 characters are truncated in ad placements and shopping surfaces, reducing CTR.",
    category: "Content",
  },
  {
    id: "i6",
    title: "Missing Material Attribute",
    count: 312,
    impact: "Medium",
    revenueAtRisk: "$1.2K",
    suppressedImpressions: "45K",
    description: "Material is required for Apparel categories in Google Shopping XML feeds. Items are partially suppressed.",
    category: "Attributes",
  },
  {
    id: "i7",
    title: "Duplicate Product IDs",
    count: 8,
    impact: "High",
    revenueAtRisk: "$900",
    suppressedImpressions: "5K",
    description: "Multiple items share the same ID. This causes sync conflicts and overwrites in the master catalog.",
    category: "System",
  },
  {
    id: "i8",
    title: "Missing Color for Variants",
    count: 145,
    impact: "Medium",
    revenueAtRisk: "$2.4K",
    suppressedImpressions: "38K",
    description: "Variant items must have a color attribute to be eligible for dynamic remarketing campaigns.",
    category: "Attributes",
  },
  {
    id: "i9",
    title: "Invalid URL Format",
    count: 24,
    impact: "High",
    revenueAtRisk: "$4.1K",
    suppressedImpressions: "12K",
    description: "Product links are broken or non-standard. Users cannot reach the landing page upon clicking ads.",
    category: "Navigation",
  },
  {
    id: "i10",
    title: "Stale Price in Feed",
    count: 18,
    impact: "Medium",
    revenueAtRisk: "$1.1K",
    suppressedImpressions: "9K",
    description: "Prices in the feed updated > 24h ago but haven't synced with the website. Potential for price mismatches.",
    category: "Pricing",
  },
  {
    id: "i11",
    title: "Image Linked to 404",
    count: 42,
    impact: "High",
    revenueAtRisk: "$5.2K",
    suppressedImpressions: "84K",
    description: "Primary image URL returns a 404 error. Critical impact on ad conversion and trust.",
    category: "Media",
  },
  {
    id: "i12",
    title: "Missing Age Group",
    count: 812,
    impact: "Low",
    revenueAtRisk: "$800",
    suppressedImpressions: "22K",
    description: "Age group is recommended for all apparel. Defaults to 'Adult' but may affect precision targeting.",
    category: "Demographics",
  },
  {
    id: "i13",
    title: "Shipping Weight Missing",
    count: 64,
    impact: "Low",
    revenueAtRisk: "$200",
    suppressedImpressions: "3K",
    description: "Missing shipping weight affects calculated shipping costs in certain regions, causing checkout friction.",
    category: "Logistics",
  },
  {
    id: "i14",
    title: "Non-SSL Landing Page",
    count: 4,
    impact: "High",
    revenueAtRisk: "$12K",
    suppressedImpressions: "15K",
    description: "Landing pages must be served over HTTPS. Google Merchant Center will suspend these products.",
    category: "Security",
  },
  {
    id: "i15",
    title: "Promotional Text in Title",
    count: 122,
    impact: "Low",
    revenueAtRisk: "$350",
    suppressedImpressions: "14K",
    description: "Titles containing 'Free Shipping' or 'Sale' are against Google policy and may be suppressed.",
    category: "Policy",
  },
  {
    id: "i16",
    title: "Missing Size System",
    count: 56,
    impact: "Medium",
    revenueAtRisk: "$1.4K",
    suppressedImpressions: "18K",
    description: "Required for sizing disambiguation (e.g., US vs UK). Affects filter accuracy in search results.",
    category: "Attributes",
  },
  {
    id: "i17",
    title: "Brand Name Mismatch",
    count: 12,
    impact: "Medium",
    revenueAtRisk: "$2.8K",
    suppressedImpressions: "9K",
    description: "Feed brand vs website schema brand mismatch. Reduces brand authority and search indexing.",
    category: "Content",
  },
  {
    id: "i18",
    title: "Out of Stock (Suppressed)",
    count: 144,
    impact: "Low",
    revenueAtRisk: "—",
    suppressedImpressions: "24K",
    description: "Items marked as out-of-stock but still present in feed. Automatically suppressed to prevent wasted spend.",
    category: "Inventory",
  },
]

export const catalogCategoryPerformance = [
  { name: "Sneakers",    productCount: 31200, share: 25, roas: "12.4x", cvr: "2.12%", revenue: "$45.2K", trend: "up"   },
  { name: "Apparel",     productCount: 28600, share: 23, roas: "6.8x",  cvr: "1.42%", revenue: "$22.4K", trend: "down" },
  { name: "Luxury Bags", productCount: 22840, share: 18, roas: "8.4x",  cvr: "1.84%", revenue: "$38.1K", trend: "up"   },
  { name: "Shoes",       productCount: 18400, share: 15, roas: "7.2x",  cvr: "1.68%", revenue: "$19.6K", trend: "up"   },
  { name: "Accessories", productCount: 14652, share: 12, roas: "4.5x",  cvr: "1.24%", revenue: "$12.8K", trend: "up"   },
  { name: "Watches",     productCount:  9200, share:  7, roas: "10.8x", cvr: "0.92%", revenue: "$14.3K", trend: "up"   },
]

// ─── Publishers Mock Data ─────────────────────────────────────────────────────

export const publisherMetrics = [
  {
    title: "Total Publishers",
    value: "47",
    description: "Active network partners",
    icon: Globe,
    trend: "up",
    change: "+12",
    context: "this quarter",
  },
  {
    title: "Total Impressions",
    value: "5.15M",
    description: "Aggregate reach (30d)",
    icon: BarChart3,
    trend: "up",
    change: "+18%",
    context: "month-over-month",
  },
  {
    title: "Network Revenue",
    value: "$72.4K",
    description: "Last 30 days total",
    icon: TrendingUp,
    trend: "up",
    change: "+24%",
    context: "MoM",
  },
  {
    title: "Avg. Publisher CVR",
    value: "1.84%",
    description: "Baseline conversion",
    icon: Zap,
    trend: "up",
    change: "+53%",
    context: "above market avg",
  },
]

export const networkSegments = [
  {
    name: "Realry AI Engine",
    impressions: "2.2M",
    roas: "11.0x",
    status: "active",
    icon: Bot,
    color: "text-blue-600",
    bg: "bg-blue-50 dark:bg-blue-900/30",
  },
  {
    name: "StylMatch Network",
    impressions: "980K",
    roas: "9.4x",
    status: "active",
    icon: Users,
    color: "text-purple-600",
    bg: "bg-purple-50 dark:bg-purple-900/30",
  },
  {
    name: "DailyClick DSP",
    impressions: "1.4M",
    roas: "6.8x",
    status: "active",
    icon: Globe,
    color: "text-emerald-600",
    bg: "bg-emerald-50 dark:bg-emerald-900/30",
  },
  {
    name: "Sneakers123 + FlexDog",
    impressions: "1.1M",
    roas: "10.4x",
    status: "active",
    icon: Zap,
    color: "text-amber-600",
    bg: "bg-amber-50 dark:bg-amber-900/30",
  },
]

export type PublisherType = "Owned Media" | "Embedded" | "Whitelisted" | "Direct Deal"

export const publishersList: {
  id: string
  name: string
  type: PublisherType
  impressions: string
  cvr: string
  revenue: string
  roas: string
  status: "active" | "paused" | "pending"
  campaigns: number
}[] = [
  {
    id: "p0a",
    name: "Realry Search",
    type: "Owned Media",
    impressions: "2.2M",
    cvr: "1.45%",
    revenue: "$32.8K",
    roas: "11.0x",
    status: "active",
    campaigns: 4,
  },
  {
    id: "p0b",
    name: "StylMatch Creators",
    type: "Owned Media",
    impressions: "980K",
    cvr: "1.64%",
    revenue: "$21.6K",
    roas: "9.4x",
    status: "active",
    campaigns: 3,
  },
  {
    id: "p1",
    name: "DailyClick Network",
    type: "Embedded",
    impressions: "1.2M",
    cvr: "2.1%",
    revenue: "$28.4K",
    roas: "9.2x",
    status: "active",
    campaigns: 4,
  },
  {
    id: "p2",
    name: "Sneakers123",
    type: "Direct Deal",
    impressions: "620K",
    cvr: "4.5%",
    revenue: "$12.1K",
    roas: "11.8x",
    status: "active",
    campaigns: 2,
  },
  {
    id: "p3",
    name: "FlexDog",
    type: "Direct Deal",
    impressions: "480K",
    cvr: "3.8%",
    revenue: "$9.4K",
    roas: "9.6x",
    status: "active",
    campaigns: 2,
  },
  {
    id: "p4",
    name: "StyleWire Editorial",
    type: "Whitelisted",
    impressions: "850K",
    cvr: "1.8%",
    revenue: "$15.6K",
    roas: "6.4x",
    status: "active",
    campaigns: 2,
  },
  {
    id: "p5",
    name: "HighSnobiety",
    type: "Whitelisted",
    impressions: "380K",
    cvr: "1.2%",
    revenue: "$8.2K",
    roas: "5.1x",
    status: "active",
    campaigns: 1,
  },
  {
    id: "p6",
    name: "Vogue UK Digital",
    type: "Whitelisted",
    impressions: "290K",
    cvr: "0.9%",
    revenue: "$6.8K",
    roas: "4.4x",
    status: "active",
    campaigns: 1,
  },
  {
    id: "p7",
    name: "Lyst",
    type: "Direct Deal",
    impressions: "—",
    cvr: "—",
    revenue: "—",
    roas: "—",
    status: "pending",
    campaigns: 0,
  },
  {
    id: "p8",
    name: "Facebook Shops",
    type: "Embedded",
    impressions: "2.4M",
    cvr: "1.2%",
    revenue: "$18.4K",
    roas: "6.2x",
    status: "active",
    campaigns: 3,
  },
  {
    id: "p9",
    name: "Instagram Checkout",
    type: "Embedded",
    impressions: "1.8M",
    cvr: "1.5%",
    revenue: "$22.1K",
    roas: "7.8x",
    status: "active",
    campaigns: 5,
  },
  {
    id: "p10",
    name: "Pinterest Shopping",
    type: "Embedded",
    impressions: "950K",
    cvr: "0.8%",
    revenue: "$7.2K",
    roas: "4.5x",
    status: "active",
    campaigns: 2,
  },
  {
    id: "p11",
    name: "TikTok Shop",
    type: "Embedded",
    impressions: "3.2M",
    cvr: "2.1%",
    revenue: "$45.6K",
    roas: "12.4x",
    status: "active",
    campaigns: 4,
  },
  {
    id: "p12",
    name: "Hypebeast",
    type: "Whitelisted",
    impressions: "420K",
    cvr: "1.4%",
    revenue: "$9.8K",
    roas: "5.4x",
    status: "active",
    campaigns: 1,
  },
  {
    id: "p13",
    name: "Complex",
    type: "Whitelisted",
    impressions: "310K",
    cvr: "0.9%",
    revenue: "$6.4K",
    roas: "4.2x",
    status: "active",
    campaigns: 1,
  },
  {
    id: "p14",
    name: "GQ Online",
    type: "Whitelisted",
    impressions: "250K",
    cvr: "1.1%",
    revenue: "$5.2K",
    roas: "4.8x",
    status: "active",
    campaigns: 1,
  },
  {
    id: "p15",
    name: "Esquire Digital",
    type: "Whitelisted",
    impressions: "180K",
    cvr: "0.7%",
    revenue: "$3.1K",
    roas: "3.4x",
    status: "active",
    campaigns: 1,
  },
  {
    id: "p16",
    name: "ShopStyle",
    type: "Embedded",
    impressions: "1.5M",
    cvr: "1.8%",
    revenue: "$32.4K",
    roas: "9.2x",
    status: "active",
    campaigns: 6,
  },
  {
    id: "p17",
    name: "Farfetch Network",
    type: "Whitelisted",
    impressions: "850K",
    cvr: "2.4%",
    revenue: "$52.1K",
    roas: "11.8x",
    status: "active",
    campaigns: 3,
  },
  {
    id: "p18",
    name: "MyTheresa",
    type: "Direct Deal",
    impressions: "320K",
    cvr: "3.1%",
    revenue: "$15.6K",
    roas: "8.4x",
    status: "active",
    campaigns: 2,
  },
  {
    id: "p19",
    name: "SSENSE",
    type: "Direct Deal",
    impressions: "450K",
    cvr: "2.8%",
    revenue: "$24.4K",
    roas: "9.6x",
    status: "active",
    campaigns: 2,
  },
  {
    id: "p20",
    name: "End Clothing",
    type: "Direct Deal",
    impressions: "210K",
    cvr: "1.2%",
    revenue: "$8.4K",
    roas: "4.2x",
    status: "paused",
    campaigns: 0,
  },
  {
    id: "p21",
    name: "Grailed",
    type: "Whitelisted",
    impressions: "1.1M",
    cvr: "1.9%",
    revenue: "$38.2K",
    roas: "10.2x",
    status: "active",
    campaigns: 3,
  },
  {
    id: "p22",
    name: "StockX",
    type: "Direct Deal",
    impressions: "2.5M",
    cvr: "3.4%",
    revenue: "$92.1K",
    roas: "14.2x",
    status: "active",
    campaigns: 4,
  },
  {
    id: "p23",
    name: "GOAT",
    type: "Whitelisted",
    impressions: "1.6M",
    cvr: "2.5%",
    revenue: "$58.4K",
    roas: "11.1x",
    status: "active",
    campaigns: 3,
  },
  {
    id: "p24",
    name: "Stadium Goods",
    type: "Whitelisted",
    impressions: "480K",
    cvr: "1.6%",
    revenue: "$12.4K",
    roas: "6.8x",
    status: "active",
    campaigns: 2,
  },
]
