/** Flag emoji for region labels in the campaign wizard (readable at small sizes). */
const REGION_FLAGS: Record<string, string> = {
  "United Kingdom": "🇬🇧",
  "United States": "🇺🇸",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  "New Zealand": "🇳🇿",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Italy: "🇮🇹",
  Spain: "🇪🇸",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Austria: "🇦🇹",
  Switzerland: "🇨🇭",
  Ireland: "🇮🇪",
  Portugal: "🇵🇹",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Denmark: "🇩🇰",
  Finland: "🇫🇮",
  Poland: "🇵🇱",
  "Czech Republic": "🇨🇿",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Singapore: "🇸🇬",
  "Hong Kong": "🇭🇰",
  Taiwan: "🇹🇼",
  India: "🇮🇳",
  Thailand: "🇹🇭",
  Malaysia: "🇲🇾",
  Indonesia: "🇮🇩",
  Philippines: "🇵🇭",
  "United Arab Emirates": "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  Israel: "🇮🇱",
  "South Africa": "🇿🇦",
  Brazil: "🇧🇷",
  Mexico: "🇲🇽",
  Argentina: "🇦🇷",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
}

export function regionFlag(region: string): string {
  return REGION_FLAGS[region] ?? "🌍"
}
